name: fake_phonepe
description: PhonePe clone
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_tts: ^4.0.2
  audioplayers: ^6.1.0
  mobile_scanner: ^5.2.3
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/phonepe_success.mp3
    - assets/phonepe_ding.mp3
